### ISSUE TITLE
wordnet high performance

### ISSUE THREAD

**Issue by vyhuhol** [morungos/wordnet#11]
Hi morungos,

Again thank you very much for this project.

I want to know your advise. I use wordnet for some pretty heavy task, the task is running on a big server. I need good performance from wordnet package. Caching doesn't seem to help much. 

What do you think is the best way to improve performance?
Can I place the entire wordnet in memory and use it. I guess it will be faster than reading from files.

**Comment by morungos** [comment]
First of all,  I'd be interesting in hearing if you have a small enough or open enough system that I can use it for benchmarking. I'm happy to assess and improve performance, but I need heavier duty tests to do that. 

Wordnet is I/O heavy, so placing the database on a ramfs or similar (as you suggest) should remove the disk bottlenecks, as would using an SSD. I admit most of my work uses an SSD so I might be getting more performance for that reason. Essentially: disk seek time and latency becomes irrelevant. But I suspect there are algorithmic things I can do too, which I haven't done, such as using mmap for file access rather than buffered reading (which I stole and improved from the original port). 

Others have, I know, simply moved Wordnet data into SQLite databases so the lookup code is in C rather than JS. That would probably make a difference, but it isn't the Wordnet native format so it would be a major change. 

I'd say the way forward is to get a test set that demonstrates the problem well enough that we can profile it and focus on the best performance improvements we can make.

**Comment by morungos** [comment]
I've added a benchmarking issue #15, and started on that. So far, performance looks very decent, but the file system could certainly have a significant effect. I'm closing for now as this was more discussion, and the benchmarking will cover real performance issues.
