### ISSUE TITLE
webpack

### ISSUE THREAD

**Issue by simdax** [morungos/wordnet#26]
Hello.

How is it possible to make your librarie webpack compatible.
I am trying to use it with a simple webpack configuration, and I have this error
![screen shot 2018-04-27 at 10 05 35 pm](https://user-images.githubusercontent.com/2458806/39382820-2642962e-4a67-11e8-907d-d1149ba901aa.png)

Thank you!

**Comment by morungos** [comment]
It probably isn’t unfortunately. WordNet is a collection of very large files, and embedding them into a browser is not a simple way forward. At least not yet. So this module is intended mainly for Node.js and it’s file system libraries. If we were going to build an embeddable version (and this might be something useful) we’d look at a very different file format to make it smaller and faster. It’s not on our current road map, unfortunately. 

For now, the easiest solution is make a RESTful API for the data you need and access it that way. If you really need a client embeddable form, then let me know and I’ll see if I can work out what might be a viable solution.

**Comment by morungos** [comment]
Closing -- this isn't going to happen due to the misery of rewriting all the file access parts. At least, not for now. It might be worth considering a minimal DB version, which could be handy for embedding. I think WordNet has a mini DB version dataset, but it is probably best handled as a separate module with an identical API.
