### ISSUE TITLE
Missing Dependancy

### ISSUE THREAD

**Issue by silentrob** [morungos/wordnet#4]
https://github.com/morungos/wordnet/blob/develop/lib/wordnet.js#L25

You have it listed as a dev-dep and not a normal dependancy.

**Comment by morungos** [comment]
Actually, this was intentional. What I'd thought was that someone using: `npm install` should get it, but that someone using `npm install --production` wouldn't, on the assumption they might have a version of WordNet elsewhere and were pointing to it by passing its directory to the constructor. That allows someone in production use to not throw the whole of WordNet into `node_modules`. Also, if someone really wanted to use WordNet, they could make it a dependency of their application directly and pick it up from there. 

What do you think? Should WordNet just be downloaded and used as is?

**Comment by silentrob** [comment]
I didn't get it with `npm install` and I would expect that flow to work.

I actually didn't even know about `npm install --production` and Ive been using node since 0.0.25 (that's the versioning system before 0.2.0 :)

**Comment by morungos** [comment]
Ah, I see the issue. devDependencies are only installed one level deep in a normal (non-dev, non production) install! So, yes, if you use the module, you'd need to explicitly add `wndb-with-exceptions` as a dependency at the package level too. Yes, that is something of a pain. I didn't see that as in testing I get the dev dependency, but an app that depends on `wordnet` won't get `wndb-with-exceptions` automatically.

I'd wanted to spare people the need to always have to download *my* version of WNdb (which is mainly there because I couldn't figure out how to use anyone else's and deploy the exception files into the same directory (sadly due to timing issues on dependencies in npm). I've subsequently realised that (a) the exception files and exception handling could easily be a separate module, along with the files, and (b) probably it should maybe be a peer dependency rather than a dev dependency (i.e., it's almost as if it's a plugin to WNdb, just one that's essential to use it). 

I'll try a few permutations and see what shows up. Good call, and thanks for spending time discussing this as it helped focus on the precise issue.

**Comment by silentrob** [comment]
Ah I see. Thanks for explaining that. BTW, thanks for the expanding the API. querySense is a great addition and I was in the middle of adding it myself 2 weeks back. You beat me to it!
