### ISSUE TITLE
Example of working with cache

### ISSUE THREAD

**Issue by vyhuhol** [morungos/wordnet#9]
Thank you very much for the great work.

I wonder if you can add to the description how exactly can I use cache with wordnet, preferably with possible parameters.

Thank you.

**Comment by morungos** [comment]
Good question. The best place to start is probably the test: test/wordnet_cache_test.coffee, which contains a few examples. The short version is, all you need is: 

```
var wn = new Wordnet({cache: true});
```

This creates a reasonably small cache (2000 entries) and works out of the box.

If you want a more advanced version, you can pass a object of options to `node-lru` instead of `true`, and this will create a new cache for you with those parameters. Or for really advanced use, if you can make your own cache using `node-lru` or something similar, and just pass that object as the `cache` option when you call `new Wordnet`.

So, more advanced examples would be:

```
var wn = new Wordnet({cache: { max: 500, maxAge: 1000 * 60 * 60 }});

var LRU = require("lru-cache");
var wn = new Wordnet({cache: new LRU({ max: 500, maxAge: 1000 * 60 * 60 })});
```

**Comment by vyhuhol** [comment]
Great answer, thank you very much!
